theme: "story"
baseURL: "https://rmoff.github.io"
languageCode : "en-us"
title: "rmoff's random ramblings"
disqusShortname: "rmoff"
googleAnalytics: "UA-75492960-1"
paginate: 20
pygmentsStyle: pygments

params:
  author: "Robin Moffatt"
  GitHubUser: "rmoff"
  image: "images/2018/07/IMG_3647.jpg"
permalinks:
  post: /:year/:month/:day/:title/

taxonomies:
  category: categories
  tag: tag

outputs:
   home:
      - HTML
      - JSON
      - RSS
   page:
      - HTML
   section:
      - HTML
      - RSS
   taxonomy:
      - HTML
      - RSS
   taxonomyTerm:
      - HTML
      - RSS

menu:
  main:
  - name: about
    title: about
    url: /about-me/
    weight: -3
  - name: talks
    title: talks
    url: /talks/
    weight: -2
  social:
  - name: github
    title: "fab fa-github-square"
    url: https://github.com/rmoff/
    weight: -1
  - name: twitter
    title: "fab fa-twitter-square"
    url: https://twitter.com/rmoff/
    weight: -1
  - name: linkedin
    title: "fab fa-linkedin"
    url: https://www.linkedin.com/in/robinmoffatt/
    weight: -1