theme: "story"
baseURL: "https://rmoff.github.io"
languageCode : "en-us"
title: "rmoff's random ramblings"
disqusShortname: "rmoff"
googleAnalytics: "UA-75492960-1"
paginate: 20

params:
  author: "Robin Moffatt"
  GitHubUser: "rmoff"
  cover: "images/2018/07/IMG_3647.jpg"

permalinks:
  post: /:year/:month/:day/:title/

outputs:
   home:
      - HTML
      - JSON
      - RSS
   page:
      - HTML
   section:
      - HTML
      - RSS
   taxonomy:
      - HTML
      - RSS
   taxonomyTerm:
      - HTML
      - RSS

menu:
  main:
  - name: about
    title: about
    url: /about-me/
  - name: talks
    title: talks
    url: /talks/
  - name: github
    title: "fab fa-github-square"
    url: https://github.com/rmoff/
