name: GitHub Pages

on:
  push:
    branches:
     - master
    # Run every five minutes
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1                  

    - name: Install Ruby Dev                     
      run: sudo apt-get install ruby-dev

    - name: Install AsciiDoctor and Rouge
      run: sudo gem install asciidoctor rouge

    - name: Setup Hugo                           
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.75.1'

    - name: Build                                
      run: hugo

    - name: Deploy                               
      uses: peaceiris/actions-gh-pages@v3
      with:
        # deploy_key: ${{ secrets.ACTIONS_TEST_DEPLOY_KEY }}
        # external_repository: rmoff/rmoff-test.github.io
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        external_repository: rmoff/rmoff.github.io
        publish_branch: master
